apiVersion: v1
kind: Service
metadata:
  name: {{ include "shift.fullname" . }}-control
  labels:
    {{- include "shift.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "shift.name" . }}-control
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
